name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码仓库
      uses: actions/checkout@v2

    - name: 构建 Docker 镜像
      run: |
        # 构建 Docker 镜像并为其添加 "latest" 标签
        docker build . --file Dockerfile --tag lori255/base-yunzai:latest

    - name: 登录 Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: 推送 Docker 镜像
      run: |
        # 推送 "latest" 标签
        docker push lori255/base-yunzai:latest
